version: '3'
services:
  docker-sso:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - EXTERNAL_PORT=${EXTERNAL_PORT}
      - USERS_FILE=${USERS_FILE}
    ports:
      - ${EXTERNAL_PORT}:8080
    networks:
      - net

networks:
   net: